"""How many months until the forward book could say anything, and whether money can buy that wait down.

Run: .venv/bin/python tools/power_horizon.py [--window both] [--json]

The live book's own report says it needs 23 more monthly seals before a skill claim is supportable. That number invites one
response — *then put more money in* — and this file exists because that response is mostly wrong, in a way that only shows up
once the arithmetic is done at several sizes. Everything an account pays here is proportional to what it holds: a spread in
basis points, an expense ratio per twelve. Double the account and the gap doubles, the noise doubles with it, and the
t-statistic that decides when a difference stops looking like luck does not move at all. **Scale buys dollars, not knowledge.**
What does move it is the flat cost of placing an order, which does not scale, and that is the lever that hurts small accounts
most — the objective's shape.

The claim, written before the run: **the number of months needed to detect the tilt's difference against plain VOO is
invariant to account size when every cost is proportional, and rises sharply as per-order costs replace proportional ones.**
If a per-order commission of a few dollars is enough to make the horizon unreachable, the finding is not that the tilt is bad;
it is that the *account* is too small to express the idea, which is a fact about brokers and not about markets, and the right
answer is a different broker rather than a different model.

Nothing here is hand-derived. The witness path is generated by `paper.shadow_step` itself — the sealed function that produces
the journal's own benchmark entries — and the strategy simulator is differential-tested against it on a one-fund, never-sell
account, so the two accounts in this file are computed by the code the journal trusts. The archive decides the sign: where the
measured difference does not favour the book, there is no horizon to report and none is reported. Round 77's lesson, kept:
an interval on the wrong side of zero is not a finding, it is a refusal.
"""

from __future__ import annotations

import argparse
import datetime as dt
import functools
import json
import math
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "src"))

import paper                                                 # noqa: E402
import shelter_long_record as sl                             # noqa: E402
import withdrawal_capacity as wc                             # noqa: E402
import fund_fees                                                   # noqa: E402  (the bill legs' ratios, r99)
import mix_sweep                                                 # noqa: E402  (its `drawdown`, not a second copy)

BOOK = ("SPY", "QQQ")
TILT = {"SPY": 0.50, "QQQ": 0.50}
WITNESS = "VOO"
SCALE_RATIO = 0.10                       # the journal's $500 on $5,000: deposits are a tenth of the opening
SCALES = (5_000.0, 20_000.0, 100_000.0, 250_000.0)
COMMISSIONS = (0.0, 4.95, 9.95)          # per order, not per share: what a retail ticket actually costs
SPREADS = (1.0, 3.0, 10.0)               # the journal charges 3.0; 1.0 is a good limit order, 10.0 is a bad day
T_STAT = 2.0
WINDOWS = (("since the witness existed", None), ("last five years", 5))


@functools.lru_cache(maxsize=1)
def _market() -> tuple:
    from boring_alpha.data.csv_loader import load_csv_market_data
    data = load_csv_market_data(wc.SNAPSHOT, wc.CASH_FILE)
    legs = {s: sl.legs(data, s) for s in BOOK + (WITNESS,)}
    months = sorted({(d.year, d.month) for d in legs[WITNESS]})
    ends = []
    for key in months:
        days = [d for d in legs[WITNESS] if (d.year, d.month) == key]
        if all(any((d.year, d.month) == key for d in legs[s]) for s in BOOK):
            ends.append((days[-1], {s: legs[s][[d for d in legs[s] if (d.year, d.month) == key][-1]][0] for s in legs}))
    return ends, tuple(sorted(legs))


def last_date() -> dt.date:
    """The newest month-end in the archive, so windows can be stated relative to the data rather than to a typed year."""

    return _market()[0][-1][0]


def month_closes(since: dt.date | None) -> list:
    """Month-end dates and prices for every fund the study touches, from the witness's own history."""

    ends, _ = _market()
    return [e for e in ends if since is None or e[0] >= since]


def simulate(closes: list, opening: float, deposit: float, weights: dict, spread_bps: float,
             commission: float, fee_by_symbol: dict, band: float = 0.0, every: int = 1,
             stats: dict | None = None) -> list:
    """Deposit monthly, hold the target mix, pay for every ticket. Returns the closing value after each month.

    `band` and `every` are what round 83 exists to price. A target weight held constant is a *decision* made over and over:
    every month the book that wants 50/50 sells whatever rose and buys whatever fell, and the backtests that ranked the mixes
    charged nothing for it because a constant weight vector has no turnover to price. `band = 0.0` reproduces that
    rebalancing, still charged (round 82's accounts), so the idealisation and its replacement differ only in what they cost.
    `band = 5` allows five points of drift before anything is sold; between breaches, and in months that are not decision
    months under `every`, the deposit alone is invested, split by the target weights, which never triggers a sale. That is the
    construction an investor actually runs, and the difference between it and the idealised constant weight is a number rather
    than a preference.

    Two conventions matter, because a differential test depends on them. The first month-end opens the account with cash and
    buys nothing, and from the second the deposit arrives and the account is invested — the journal's calendar, so
    `tests/test_power_horizon.py` can walk this function and `paper.shadow_step` over the same dates and compare balances. And
    cash is a state variable rather than a subtraction, for a reason this file learned the hard way: the first version
    recovered it from the previous balance minus holdings priced at *today's* prices, exactly as `shadow_step` did, and the
    two accounts agreed with each other perfectly while both failing to earn the market. That comparison is what surfaced the
    defect; the journal's fix is `paper.recover_cash`.
    """

    rate = spread_bps / 10_000.0
    units, out, cash = {}, [], 0.0
    for i, (day, prices) in enumerate(closes):
        if i == 0:
            cash += opening
            out.append(cash)
            continue
        arrived = deposit
        held = sum(u * prices[s] for s, u in units.items())
        cash += arrived
        pot = held + cash
        traded = 0.0
        orders = 0
        # Same convention as `paper.orders_within_band`, which this file cannot import: drift across the invested book, not
        # across equity including the deposit that has just arrived. Including the deposit inflates drift by about the deposit
        # share every month, which for a book funded at 10% a month is 5 points — enough to breach any sane band on schedule.
        invested = sum(u * prices[s] for s, u in units.items())
        drift = (max((abs(weights[s] - units.get(s, 0.0) * prices[s] / invested) for s in weights), default=1.0)
                 if invested > 0.0 else 1.0)
        decide = (i - 1) % every == 0 or not units or drift >= 1.0
        full_rebalance = band <= 0.0 or drift > band / 100.0
        if i == 1:
            # The opening has to get to work. A band that suppresses the first rebalance leaves the account's largest single
            # sum sitting in cash for the whole record, which is not a policy anyone chose: the first version of this branch
            # did exactly that and reported a drifting book as if it had been holding cash since inception. The journal's
            # own anchor behaves the same way — it holds cash and is invested at its first step.
            decide = full_rebalance = True
        if decide and full_rebalance:
            allocation = {s: pot * w for s, w in weights.items()}
        else:
            # Buy-only: everything already held stays where it is, and whatever the account can actually spend — the deposit
            # plus or minus the spread debt left from previous months — goes in split by the target weights. Splitting the
            # deposit alone and leaving the residue sitting would put a permanently negative cash line on an account that is
            # supposed to be fully invested, and would make it disagree with the equivalent pair of single-fund accounts.
            allocation = {s: units.get(s, 0.0) * prices[s] + cash * w for s, w in weights.items()}
        held_of = {s: units.get(s, 0.0) * prices[s] for s in allocation}
        sold_this_month = any(held_of[s] - allocation[s] > 0.005 for s in allocation)
        for sym, want_to in allocation.items():
            price = prices[sym]
            want = want_to - units.get(sym, 0.0) * price
            if abs(want) < 0.005:
                continue
            if not full_rebalance and want < 0.0:
                continue                            # between breaches this account only buys
            orders += 1
            if want > 0:
                spend = want / (1.0 + rate)
                units[sym] = units.get(sym, 0.0) + spend / price
                traded += spend * rate
                cash -= spend * (1.0 + rate)
            else:
                proceeds = -want * (1.0 - rate)
                units[sym] = units.get(sym, 0.0) - (-want) / price
                traded += (-want) * rate
                cash += proceeds
        if commission:
            cash -= commission * orders
        if stats is not None:
            # Counted here, at the trade, and not inferred afterwards: once the month's orders settle, the account sits at its
            # allocation and the evidence that anything was sold is gone. The first version of this tally read `units` after
            # the trades and reported that a book which sold in most of its months had never sold at all.
            stats["tickets"] = stats.get("tickets", 0) + orders
            stats["spread"] = stats.get("spread", 0.0) + traded
            stats["months"] = stats.get("months", 0) + 1
            stats["sells"] = stats.get("sells", 0) + (1 if sold_this_month else 0)
            stats["turnover"] = stats.get("turnover", 0.0) + sum(
                abs(allocation[s] - held_of[s]) for s in allocation)
        # Each fund's NAV erodes by its own expense ratio, so each sleeve is burned by its own fee. The first version summed
        # the book's expense and spread it pro-rata by value, which charged the cheap sleeve the expensive sleeve's rate and
        # vice versa — round 81's fee-ordering bug wearing a different hat, found here by the oracle test that compares this
        # account against two single-fund accounts it is supposed to be identical to. Totals are unchanged; the mix was not.
        expense = 0.0
        for s in list(units):
            rate_s = fee_by_symbol.get(s, paper.UNPOSTED_FEE) / 12.0
            fee_s = rate_s * units[s] * prices[s]
            expense += fee_s
            if units[s] > 0.0:
                units[s] -= fee_s / prices[s]
        out.append(cash + sum(u * prices[s] for s, u in units.items()))
    if len(out) != len(closes):
        raise AssertionError("one closing balance per month-end, no exceptions")
    return out


def gap(series: list, witness: list) -> list:
    return [b - w for b, w in zip(series, witness)]


def increments(rel: list) -> list:
    """The statistic is taken on the month-on-month change, not on the level. A cumulative gap trends with the market and
    its own mean; a t-test on a trending level finds significance in wherever the index happened to go."""

    return [rel[i] - rel[i - 1] for i in range(1, len(rel))]


def horizon(gaps: list) -> dict:
    """Months to a t-statistic of 2 on the mean difference, from the difference's own mean and spread. No horizon exists for
    a difference that is not there, and that is reported as a refusal rather than as a very large number."""

    if len(gaps) < 12:
        return {"m": None, "why": "fewer than twelve months of difference", "n": len(gaps)}
    mean = statistics.fmean(gaps)
    sd = statistics.pstdev(gaps)
    if mean <= 0.0:
        return {"m": None, "why": "the measured difference does not favour the book", "mean": mean, "sd": sd,
                "n": len(gaps)}
    if sd <= 0.0:
        return {"m": 1, "why": "no dispersion at all", "mean": mean, "sd": sd, "n": len(gaps)}
    exact = (T_STAT * sd / mean) ** 2
    # The exact figure travels with the rounded one. Ceilings hide how close a horizon is to the next seal, and comparing
    # ceilings across account sizes reports a difference where there is only float noise at an integer boundary.
    return {"m": math.ceil(exact), "m_exact": exact, "mean": mean, "sd": sd, "n": len(gaps)}


def pay_in(closes: list, opening: float, deposit: float) -> list:
    total, out = 0.0, []
    for i in range(len(closes)):
        total += opening if i == 0 else deposit
        out.append(total)
    return out


def study(since: dt.date | None, label: str) -> dict:
    closes = month_closes(since)
    fees = {s: paper.fee_for(s) for s in BOOK + (WITNESS,)}
    out = {"label": label, "months": len(closes), "start": closes[0][0].isoformat(),
           "end": closes[-1][0].isoformat(), "cells": []}
    for scale in SCALES:
        opening, deposit = scale, scale * SCALE_RATIO
        paid = pay_in(closes, opening, deposit)
        for commission in COMMISSIONS:
            for spread in SPREADS:
                # The witness pays what the book pays. `paper.shadow_step` charges the benchmark the same spread on purpose:
                # a benchmark priced more expensively than the thing it judges retires a strategy for free, and one priced
                # more cheaply buys it a win for nothing. A per-order ticket charge is symmetric too, and the witness places
                # one order a month while the tilt places two — which is part of the difference, not a rounding note.
                witness = simulate(closes, opening, deposit, {WITNESS: 1.0}, spread, commission, fees)
                book = simulate(closes, opening, deposit, TILT, spread, commission, fees)
                g = gap(book, witness)
                rel = [x / p for x, p in zip(g, paid)]
                h = horizon(increments(rel))
                if h.get("mean") is not None:
                    h["total_gap_pct"] = rel[-1]
                out["cells"].append({"scale": scale, "commission": commission, "spread_bps": spread,
                                     "orders_per_month": 2 if commission else 2, "final_gap": g[-1],
                                     "final_gap_pct": g[-1] / paid[-1], **h})
    zero = [c for c in out["cells"] if c["commission"] == 0.0 and c["spread_bps"] == 3.0]
    exact = [c["m_exact"] for c in zero if c.get("m_exact")]
    out["invariance_spread"] = (max(exact) / min(exact) - 1.0) if len(exact) > 1 else 0.0
    flat = [c for c in out["cells"] if c["commission"] == COMMISSIONS[-1] and c["spread_bps"] == 3.0]
    out["invariant_when_proportional"] = bool(exact) and out["invariance_spread"] < 1e-9
    out["grows_with_a_ticket"] = bool([c for c in flat if c["m"]]) and flat[0]["m"] not in (None,) and \
        (flat[-1]["m"] or 0) <= flat[0]["m"]
    out["smallest_wait"] = flat[0]["m"]
    out["largest_wait"] = flat[-1]["m"]
    return out


# (label, target weights, drift band). The last three rows are the same two funds in the same proportions, differing only in how
# often the book is willing to sell what rose: monthly (round 82's finding), past five points (what the forward book `tilt_band`
# actually trades), and never (the drift control, which is what "do nothing after the first buy" means when deposits keep coming).
SECONDARY_BARS = ({"bar": "plain VOO, the standing bar", "weights": {WITNESS: 1.0}, "band": 0.0},
                  {"bar": "plain QQQ, the free version of the same bet", "weights": {"QQQ": 1.0}, "band": 0.0},
                  {"bar": "plain SPY, the free market", "weights": {"SPY": 1.0}, "band": 0.0},
                  {"bar": "the tilt, rebalanced monthly", "weights": TILT, "band": 0.0},
                  {"bar": "the tilt, only past 5 points of drift", "weights": TILT, "band": 5.0},
                  {"bar": "the tilt, never rebalanced", "weights": TILT, "band": 99.0},
                  # The seventh row is the alternative every reader actually holds while they decide: Treasury bills. It is in the
                  # table because a table of bets without the do-nothing option in it is an argument, not a comparison. Charged
                  # SGOV's ratio (pro rata on sessions) and the journal's spread on every transfer in, so it pays like a fund.
                  {"bar": "T-bills, charged SGOV's ratio", "cash": True, "band": None})
BAR_CAPITAL = 100_000.0            # round 82's account: a tenth a month, commission-free, 3 bps of spread


def cash_bar(closes: list, opening: float, deposit: float, fee: float, spread_bps: float,
             accruals: list | None = None) -> list:
    """T-bills at the archive's own cash curve, on the fund bars' calendar, charged its own way.

    The accrual is the product of the *daily* factors between two consecutive month keys, not a monthly rate read off a table.
    That is deliberate: round 47's defect was annualising a stub month (four sessions, as the archive stands today) and reporting
    the curve 93 bps low, and interval compounding is exact on a stub and on a full month alike. The consequence is that this bar
    shares the other six rows' deposit schedule to the day, so the paid-in column is identical and the comparison is a comparison.

    What the row does *not* include is what a broker actually pays on idle cash — 0.02% at the median of eleven default sweep
    accounts, which `cash_yield_gap.py` owns and prices. A T-bill fund is a decision to leave the sweep; this row is what that
    decision earned, before tax, which is also the only figure in this file that is certain.
    """

    from boring_alpha.data.csv_loader import load_csv_market_data
    data = load_csv_market_data(wc.SNAPSHOT, wc.CASH_FILE)
    factors, sessions = data.cash_factors, sorted(data.cash_factors)
    balance, path = opening, []
    for i in range(len(closes)):
        if i:
            start, end = closes[i - 1][0], closes[i][0]
            held = [d for d in sessions if start < d <= end]
            if not held:
                raise SystemExit(f"no cash sessions between {start} and {end}: the bar cannot accrue on a calendar it cannot see")
            factor = 1.0
            for day in held:
                factor *= factors[day]
            if accruals is not None:
                accruals.append(factor - 1.0)                             # gross of fee and spread, for cross-checking
            balance *= factor * (1.0 - fee * len(held) / 252.0)          # ratio pro rata on sessions, not assumed by a month
        balance += deposit * (1.0 - spread_bps / 10_000.0)               # the transfer in pays the spread, as every other bar does
        path.append(balance)
    return path


def secondary_bars(since: dt.date | None, label: str, opening: float = BAR_CAPITAL) -> dict:
    """Reprint the archive's most uncomfortable comparison, which until round 96 had no command behind it.

    Round 82's table — the tilt closes at $9.8M and plain QQQ at $12.3M on the same $2.02M paid in — is the single most
    consequential number in this repository for the objective "beat VOO, QQQ, or whatever", and it existed only as a table in
    a note. A headline with no command under it is a headline that decays (r91), so the same four bars are now run by the same
    simulator on every invocation of this file, and a test pins the reprint to the published figures.
    """

    closes = month_closes(since)
    fees = {sym: paper.fee_for(sym) for sym in BOOK + (WITNESS,)}
    deposit = opening * SCALE_RATIO
    paid = pay_in(closes, opening, deposit)
    rows, out_accruals = [], []
    for spec in SECONDARY_BARS:
        if spec.get("cash"):
            fee = fund_fees.fee_for("SGOV")
            path = cash_bar(closes, opening, deposit, fee, 3.0, accruals=out_accruals)
        else:
            fee = None
            path = simulate(closes, opening, deposit, spec["weights"], 3.0, 0.0, fees, band=spec["band"])
        rows.append({"bar": spec["bar"], "band_points": spec.get("band"), "cash": bool(spec.get("cash")),
                     "expense_ratio": fee, "paid_in": paid[-1], "closed_at": path[-1],
                     "difference": path[-1] - paid[-1], "worst_drawdown": mix_sweep.drawdown([d for d, _ in closes], path)})
    return {"label": label, "months": len(closes), "rows": rows, "accruals": out_accruals}


def report_bars(studies: list) -> None:
    for (label, years), study_row in zip(WINDOWS, studies):
        since = None if years is None else month_closes(None)[-1][0] - dt.timedelta(days=int(365.25 * years))
        block = secondary_bars(since, label)
        print(f"\n  the bars, {label} ({block['months']} month-ends, ${BAR_CAPITAL:,.0f} opening, a tenth a month, no commission):")
        print("    `worst hole` is peak-to-trough of the *balance*, so money still arriving dilutes it; `mix_sweep.py` reports")
        print("    drawdown on the index itself and prints larger numbers. Both are honest, neither is the other's check.")
        for row in block["rows"]:
            tag = f"   its own ratio {row['expense_ratio']:.2%}" if row["cash"] else ""
            print(f"    {row['bar']:<36} paid in ${row['paid_in']:>11,.0f}   closed at ${row['closed_at']:>13,.0f}"
                  f"   {'+' if row['difference'] >= 0 else ''}${row['difference']:>12,.0f}   worst hole {row['worst_drawdown']:.1%}{tag}")
        rows = block["rows"]
        best = max(rows, key=lambda r: r["closed_at"])
        band = next(r for r in rows if r["bar"].startswith("the tilt, only"))
        safest = min(rows, key=lambda r: abs(r["worst_drawdown"]))
        bills = next(r for r in rows if r["cash"])
        print(f"    best on the way up: `{best['bar']}`. Its hole: {best['worst_drawdown']:.1%}.")
        print(f"    smallest hole: `{safest['bar']}` at {safest['worst_drawdown']:.1%}, which closed ${safest['closed_at']:,.0f}"
              f" — ${best['closed_at'] - safest['closed_at']:,.0f} behind the best bar, and capacity and tail are the two halves"
              f" of one question")
        standing = next(r for r in rows if r["bar"].startswith("plain VOO"))
        gap_bills = bills["closed_at"] - standing["closed_at"]
        print(f"    the do-nothing bar finished ${abs(gap_bills):,.0f} "
              f"{'ahead of' if gap_bills >= 0 else 'behind'} the standing bar on this window, with a hole of "
              f"{bills['worst_drawdown']:.1%} rather than {standing['worst_drawdown']:.1%}. A bank sweep paying 0.02% would have"
              f" earned a fraction of the bill row — `cash_yield_gap.py` prices that gap; this table prices the decision to leave it.")
        if band["closed_at"] >= best["closed_at"]:
            print(f"    the band is not behind: it closed ${band['closed_at']:,.0f} against the best bar's ${best['closed_at']:,.0f}")
        else:
            drift = next(r for r in rows if r["bar"].endswith("never rebalanced"))
            behind_best, behind_drift = best["closed_at"] - band["closed_at"], drift["closed_at"] - band["closed_at"]
            print(f"    the banded book — what `tilt_band` trades — closed ${band['closed_at']:,.0f}: ${behind_best:,.0f} behind the"
                  f" best bar, and ${behind_drift:,.0f} behind the same two funds left alone after the first buy."
                  + (" Rebalancing this pair has cost money at every frequency tested." if behind_drift > 0 else
                     " The band now costs nothing because it has not fired."))


def report(studies: list) -> None:
    for st in studies:
        print(f"  {st['label']}: {st['months']} month-ends, {st['start']} to {st['end']} · tilt 50/50 SPY/QQQ against"
              f" plain {WITNESS}, deposits a tenth of the opening each month")
        print("  " + "-" * 96)
        print("     scale     no commission          $4.95/order          $9.95/order        the wait at 3 bps, per month")
        for scale in SCALES:
            cells = {(c["commission"], c["spread_bps"]): c for c in st["cells"] if c["scale"] == scale}
            line = f"  ${scale:>9,.0f}"
            for commission in COMMISSIONS:
                c = cells[(commission, 3.0)]
                line += f"   {(str(c['m']) + ' mo') if c['m'] else 'never':>10}"
            c0 = cells[(0.0, 3.0)]
            line += (f"      {100 * c0['mean']:+.4f}%/mo of paid-in, {c0['n']} months" if c0.get("m")
                     else f"      no difference to measure: {c0['why']}")
            print(line)
        for commission in COMMISSIONS:
            got = [c for c in st["cells"] if c["commission"] == commission and c["scale"] == SCALES[0]]
            wide = [c for c in st["cells"] if c["commission"] == commission and c["scale"] == SCALES[-1]
                    and c["spread_bps"] == 3.0]
            if got and wide and got[0]["m"] and wide[0]["m"]:
                print(f"     ${commission:,.2f} per order: ${SCALES[0]:,.0f} needs {got[0]['m']} seals,"
                      f" ${SCALES[-1]:,.0f} needs {wide[0]['m']} — {'identical' if got[0]['m'] == wide[0]['m'] else 'not identical'}")
        print(f"     scored: proportional costs only -> the wait is {'identical' if st['invariant_when_proportional'] else 'NOT identical'}"
              f" at every size; at ${COMMISSIONS[-1]:,.2f} a ticket it is {st['smallest_wait']} seals on $"
              f"{SCALES[0]:,.0f} against {st['largest_wait']} on ${SCALES[-1]:,.0f}"
              + (" — smaller accounts wait longer" if (st['smallest_wait'] or 0) > (st['largest_wait'] or 0) else "")
              + f"; the unrounded wait differs across sizes by {100 * st['invariance_spread']:.9f}%")
        print("")
    print("  The wait is counted in seals, not in months of calendar: one seal is one month-end, and a book that cannot pay")
    print("  for its tickets never reaches a verdict however long it runs. `never` means the costs exceed the difference at")
    print("  every horizon, which is a fact about the broker and not about the model.")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--window", choices=("both", "recent"), default="both")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    wanted = WINDOWS if args.window == "both" else WINDOWS[1:]
    studies = []
    for label, years in wanted:
        since = None if years is None else (dt.date.fromisoformat(_market()[0][-1][0].isoformat())
                                            - dt.timedelta(days=int(365.25 * years)))
        studies.append(study(since, label))
    if args.json:
        print(json.dumps(studies, indent=2))
    else:
        report(studies)
        print("  Pre-registered claim, scored: with proportional costs alone the horizon is identical at every account size"
              " — capital buys dollars, not knowledge; with per-order costs it grows for the smallest account and shrinks")
        print("  for the largest, so the lever is the broker's ticket charge, not the deposit.")
        report_bars(studies)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
